### ISSUE TITLE
test data sets list?

### ISSUE THREAD

**Issue by dreamhua82** [jingjin25/LFSSR-ATO#3]
Hi, would you please share a whole list of your test_sets list for me? 
Thanks.

**Comment by jingjin25** [comment]
@dreamhua82 

Hi, all of our test datasets were collected based on the original partition of the datasets' authors. For example, we directly used all of the 57 scenes under the subfolder 'general' of Standford Lytro Archieve, 30 scenes from the subfolder 'Testset' of Kalantari et al., and so on. 

We also listed the datasets used in Table 1. of our paper, so you can easily get the full test list after you downloading these datasets.

**Comment by dreamhua82** [comment]
Hi, I test the prtrained LFSSR model on the HCI_new test set(4 scenes), but the PSNR is only 37.64, which is far from the paper's value (38.52).

**Comment by jingjin25** [comment]
@dreamhua82  

I have checked the results and ensured the results are consistent with that reported in the paper. Maybe you can check the environment setting and try again.
