### ISSUE TITLE
About the running time？

### ISSUE THREAD

**Issue by dreamhua82** [jingjin25/LFSSR-ATO#4]
Hi, The table 4 in your paper , how do you compare the running time for different methods？ The SISR and bicubuic results is only for one view or the whole LF image？
（2） How do you use the ResLF code to test on your datasets？ 
Thanks a lot.

**Comment by jingjin25** [comment]
@dreamhua82 

Hi, (1) We compute the running time for generating the full LF image; (2) To test ResLF, we modify the code for data loading and quantitative computation to make them the same as ours.
