### ISSUE TITLE
About the scale

### ISSUE THREAD

**Issue by Nianzhen-GU** [jingjin25/LFSSR-ATO#6]
Is it possible that simply change scale = 3 to train the new model?

**Comment by jingjin25** [comment]
@Nianzhen-GU 

Hi, you can simply change the parameters of the upsampling module.

The original upsampler is:

```
up = []
for _ in range(int(math.log(self.scale,2))):
    up.append(nn.Conv2d(fn, 4*fn, 3, 1, 1, bias=True))
    up.append(nn.PixelShuffle(2))
    up.append(nn.ReLU(inplace=True))
self.upsampler = nn.Sequential(*up)
```

You can change it to:
```
up = []
for _ in range(int(math.log(self.scale,3))):
    up.append(nn.Conv2d(fn, 9*fn, 3, 1, 1, bias=True))
    up.append(nn.PixelShuffle(3))
    up.append(nn.ReLU(inplace=True))
self.upsampler = nn.Sequential(*up)
```

**Comment by Nianzhen-GU** [comment]
Thanks for answering! I have changed the parameters. However, I still encounter some errors. It is totally OK when I train 2X ATO network. But when I change all the parameters to 3, it will show the below error. 
<img width="713" alt="Screen Shot 2021-06-15 at 9 20 28 AM" src="https://user-images.githubusercontent.com/80320541/121978884-b7227800-cdbb-11eb-9e01-01fb2a38f117.png">

**Comment by jingjin25** [comment]
@Nianzhen-GU 

You need to re-prepare the training data, and name the LR data as 'img_LR_3' in the H5 file.

**Comment by Nianzhen-GU** [comment]
I still faced some problems. After I changed the scale to 3, it cannot fix to 64. 
<img width="703" alt="Screen Shot 2021-06-16 at 8 06 06 PM" src="https://user-images.githubusercontent.com/80320541/122238088-6eb9a600-cef2-11eb-9011-fd1d44d694fe.png">

**Comment by jingjin25** [comment]
@Nianzhen-GU 

Simply change the patch size to make it divisible by 3.

**Comment by Nianzhen-GU** [comment]
Problem solved, thanks!
