### ISSUE TITLE
About the PSNR/SSIM

### ISSUE THREAD

**Issue by Nianzhen-GU** [jingjin25/LFSSR-ATO#7]
Another question is how can I get the ground truth image, which size is 372*540 to calculate the PSNR? From the dataset.py or MatLab?

**Comment by jingjin25** [comment]
@Nianzhen-GU 

You can use the Matlab code LFData/PrepareData_test_Lytro.m to generate the LR and GT data for the test.

**Comment by Nianzhen-GU** [comment]
Got it, thank you!
